- affanculo
- bagascia
- bastarda
- bastardo
- bocchinara
- bocchinaro
- bocchini
- bocchino
- bokkinara
- bokkinaro
- bokkini
- bokkino
- cagare
- cagona
- cagone
- cazzata
- cazzo
- cazzone
- checca
- chiava
- chiavare
- chiavata
- chiavato
- chiavo
- ciucciami
- cogliona
- coglione
- cristo
- culattona
- culattone
- culo
- dio
- fanculo
- fica
- figa
- finocchio
- fottuta
- fottute
- fottuti
- fottuto
- frocetto
- frocio
- inculare
- inculata
- inculo
- kogliona
- koglione
- kristo
- kulattona
- kulattone
- kulo
- leccaculo
- leccamela
- leccamelo
- leccami
- madonna
- maiala
- maiale
- masturba
- masturbarsi
- masturbati
- merda
- merdosa
- merdoso
- mignotta
- minchia
- minchiona
- minchione
- minkia
- minkiona
- minkione
- pedofila
- pedofilo
- pompinara
- pompinaro
- pompini
- pompino
- porca
- porco
- puttana
- puttanata
- puttanella
- puttanona
- sborra
- sborragli
- sborrale
- sborrami
- sborrare
- scopare
- scopata
- sega
- segaiola
- segaiolo
- seghe
- sfondami
- sfondatela
- sfondatelo
- sfondati
- sperma
- stronza
- stronzata
- stronzate
- stronze
- stronzetto
- stronzi
- stronzo
- stronzone
- terrona
- terrone
- terroni
- tette
- troia
- trombando
- trombare
- trombata
- trombato
- vacca
- vaccona
- vaccone
- vaffanculo
- vaffankulo
- vakka
- vakkona
- vakkone
- zoccola
- batard
- bite
- bouse
- burne
- bâtard
- caca
- charogne
- chier
- chiotte
- con
- connard
- connerie
- couille
- cul
- daube
- encule
- enculer
- enculé
- enflure
- enfoire
- enfoiré
- foutre
- gland
- merde
- nique
- pd
- pedale
- pede
- petasse
- pipe
- pipi
- pisse
- porc
- putain
- pute
- pédale
- pédé
- pétasse
- raclure
- salop
- salope
- sucer
- trouduc
- zob
- affenarsch
- affenarsche
- arsch
- arschficker
- arschgesicht
- arschgesichter
- arschloch
- arschlocher
- arschratte
- arschratten
- auslander raus
- bastard
- blasen
- blow job
- blowjob
- blode sau
- blode saue
- bumsen
- drecksack
- drecksau
- drecksacke
- drecksaue
- endloesung
- endlosung
- fettarsch
- fettarsche
- ficken
- ficker
- fickschnitte
- fickschnitten
- fickt
- fotze
- fotzen
- fotzenlecker
- geile sau
- geile saue
- genocide
- genozid
- heil hitler
- himmler
- hitler
- homo
- hure
- huren
- hurensohn
- hurensohne
- jihad
- judensau
- judensaue
- kanacke
- kanacken
- kanake
- kanaken
- leck mich
- missgeburt
- missgeburten
- mißgeburt
- mißgeburten
- motherfucker
- mutterficker
- mose
- mosen
- nigger
- nutte
- nutten
- penner
- pissnelke
- pissnelken
- polack
- polacken
- sackratte
- sackratten
- saddam
- scheissturke
- scheissturken
- scheißturke
- scheißturken
- schlampe
- schwanzlutscher
- schwuchtel
- schwule sau
- schwule saue
- sieg heil
- stricher
- tunte
- tunten
- vergasen
- vergast
- voelkermord
- votze
- votzen
- vogeln
- vogelt
- volkermord
- wichser
- wixer
- arsche
- acojonado
- acojonar
- asaltacunas
- bandarra
- bastardo
- bollera
- cabrito
- cabronazo
- cabron
- cagada
- cagado
- cagarse
- cagarse en
- cago en
- calamar
- calientapollas
- callo
- capullo
- caraculo
- cateto
- cerdo
- chacho
- chapero
- chingado
- chorra
- chuminada
- chumino
- chupaculos
- chupapollas
- cojones
- comemierda
- comenabos
- comepollas
- cornudo
- cono
- cretino
- desgraciado
- empalmado
- empalmarse
- encular
- entrunchar
- estupido
- follar
- gilipollas
- guarra
- hijo de puta
- hijoputa
- hostia
- huevos
- huevon
- jicho
- jincho
- joder
- julandron
- julay
- kinki
- lameculos
- lamepollas
- mamonazo
- mamoncete
- mamon
- maricon
- me cago en
- mecagoendios
- mecagoenlaputa
- mecagoenlaputadeoros
- mecagoenlaputavirgen
- mecagoenlavirgensanta
- memo
- meretriz
- miembro
- mierda
- mindundi
- minga
- mingafria
- mojon
- mongolo
- mongolico
- muerdealmohadas
- obsceno
- parrus
- pederasta
- pedofilo
- pelotas
- perra
- pervertido
- picha
- pichacorta
- pichafloja
- polla
- pollada
- porculero
- porculizar
- prostituta
- puerco
- puta
- puton
- ramera
- resoplanucas
- retardado
- retrasado
- salido
- salidorro
- sarasa
- soplanucas
- soplapollas
- subnormal
- tano
- tocapelotas
- tocavainas
- tolay
- tortillera
- tranca
- trempando
- tu puta madre
- verga
- zorra
- zorron

- "ass-fucker"
- asses
- assfukka
- assholes
- asswhole
- a_s_s
- "b!tch"
- b00bs
- b17ch
- b1tch
- ballbag
- balls
- ballsack
- bastard
- beastial
- beastiality
- bellend
- bestial
- bestiality
- "bi+ch"
- bitcher
- bitchers
- bitches
- bitchin
- bitching
- blowjob
- blowjobs
- boiolas
- bollock
- bollok
- boner
- boob
- boobs
- booobs
- boooobs
- booooobs
- booooooobs
- breasts
- buceta
- bugger
- bum
- "bunny fucker"
- butt
- butthole
- buttmuch
- buttplug
- c0ck
- c0cksucker
- "carpet muncher"
- cawk
- chink
- cipa
- cl1t
- clit
- clitoris
- clits
- cnut
- cock
- "cock-sucker"
- cockface
- cockhead
- cockmunch
- cockmuncher
- cocks
- "cocksuck "
- "cocksucked "
- cocksucker
- cocksucking
- "cocksucks "
- cocksuka
- cocksukka
- cok
- cokmuncher
- coksucka
- coon
- cox
- crap
- cum
- cummer
- cumming
- cums
- cumshot
- cunilingus
- cunillingus
- cunnilingus
- cunt
- "cuntlick "
- "cuntlicker "
- "cuntlicking "
- cunts
- cyalis
- cyberfuc
- "cyberfuck "
- "cyberfucked "
- cyberfucker
- cyberfuckers
- "cyberfucking "
- d1ck
- damn
- dick
- dickhead
- dildo
- dildos
- dink
- dinks
- dirsa
- dlck
- "dog-fucker"
- doggin
- dogging
- donkeyribber
- doosh
- duche
- dyke
- ejaculate
- ejaculated
- "ejaculates "
- "ejaculating "
- ejaculatings
- ejaculation
- ejakulate
- "f u c k"
- "f u c k e r"
- f4nny
- fag
- fagging
- faggitt
- faggot
- faggs
- fagot
- fagots
- fags
- fanny
- fannyflaps
- fannyfucker
- fanyy
- fatass
- fcuk
- fcuker
- fcuking
- feck
- fecker
- felching
- fellate
- fellatio
- "fingerfuck "
- "fingerfucked "
- "fingerfucker "
- fingerfuckers
- "fingerfucking "
- "fingerfucks "
- fistfuck
- "fistfucked "
- "fistfucker "
- "fistfuckers "
- "fistfucking "
- "fistfuckings "
- "fistfucks "
- flange
- fook
- fooker
- fuck
- fucka
- fucked
- fucker
- fuckers
- fuckhead
- fuckheads
- fuckin
- fucking
- fuckings
- fuckingshitmotherfucker
- "fuckme "
- fucks
- fuckwhit
- fuckwit
- "fudge packer"
- fudgepacker
- fuk
- fuker
- fukker
- fukkin
- fuks
- fukwhit
- fukwit
- fux
- fux0r
- f_u_c_k
- gangbang
- "gangbanged "
- "gangbangs "
- gaylord
- gaysex
- goatse
- God
- "god-dam"
- "god-damned"
- goddamn
- goddamned
- "hardcoresex "
- hell
- heshe
- hoar
- hoare
- hoer
- homo
- hore
- horniest
- horny
- hotsex
- "jack-off "
- jackoff
- jap
- "jerk-off "
- jism
- "jiz "
- "jizm "
- jizz
- kawk
- knob
- knobead
- knobed
- knobend
- knobhead
- knobjocky
- knobjokey
- kock
- kondum
- kondums
- kum
- kummer
- kumming
- kums
- kunilingus
- "l3i+ch"
- l3itch
- labia
- lmfao
- lust
- lusting
- m0f0
- m0fo
- m45terbate
- ma5terb8
- ma5terbate
- masochist
- "master-bate"
- masterb8
- "masterbat*"
- masterbat3
- masterbate
- masterbation
- masterbations
- masturbate
- "mo-fo"
- mof0
- mofo
- mothafuck
- mothafucka
- mothafuckas
- mothafuckaz
- "mothafucked "
- mothafucker
- mothafuckers
- mothafuckin
- "mothafucking "
- mothafuckings
- mothafucks
- "mother fucker"
- motherfuck
- motherfucked
- motherfucker
- motherfuckers
- motherfuckin
- motherfucking
- motherfuckings
- motherfuckka
- motherfucks
- muff
- mutha
- muthafecker
- muthafuckker
- muther
- mutherfucker
- n1gga
- n1gger
- nazi
- nigg3r
- nigg4h
- nigga
- niggah
- niggas
- niggaz
- nigger
- "niggers "
- nob
- "nob jokey"
- nobhead
- nobjocky
- nobjokey
- numbnuts
- nutsack
- "orgasim "
- "orgasims "
- orgasm
- "orgasms "
- p0rn
- pawn
- pecker
- penis
- penisfucker
- phonesex
- phuck
- phuk
- phuked
- phuking
- phukked
- phukking
- phuks
- phuq
- pigfucker
- pimpis
- piss
- pissed
- pisser
- pissers
- "pisses "
- pissflaps
- "pissin "
- pissing
- "pissoff "
- poop
- porn
- porno
- pornography
- pornos
- prick
- "pricks "
- pron
- pube
- pusse
- pussi
- pussies
- pussy
- "pussys "
- rectum
- retard
- rimjaw
- rimming
- "s hit"
- "s.o.b."
- sadist
- schlong
- screwing
- scroat
- scrote
- scrotum
- semen
- sex
- "sh!+"
- "sh!t"
- sh1t
- shag
- shagger
- shaggin
- shagging
- shemale
- "shi+"
- shit
- shitdick
- shite
- shited
- shitey
- shitfuck
- shitfull
- shithead
- shiting
- shitings
- shits
- shitted
- shitter
- "shitters "
- shitting
- shittings
- "shitty "
- skank
- slut
- sluts
- smegma
- smut
- snatch
- "son-of-a-bitch"
- spac
- spunk
- s_h_i_t
- t1tt1e5
- t1tties
- teets
- teez
- testical
- testicle
- tit
- titfuck
- tits
- titt
- tittie5
- tittiefucker
- titties
- tittyfuck
- tittywank
- titwank
- tosser
- turd
- tw4t
- twat
- twathead
- twatty
- twunt
- twunter
- v14gra
- v1gra
- vagina
- viagra
- vulva
- w00se
- wang
- wank
- wanker
- wanky
- whoar
- whore
- willies
- willy
- xrated
- xxx